### ISSUE TITLE
Ability to scale the AMQ Broker to Zero

### ISSUE THREAD

**Issue by ZeidH** [Ortec-Finance/sailfish-hpc#12]
In deployments where to Sailfish is configured for a single tenant, it would be beneficial to scale the broker to zero to reduce idle resource requests on hundreds of installations that are configured for very peaky workloads.

```[tasklist]
### Tasks
- [x] AMQ Operator version is 7.11 +
- [x] Broker is configured to scale to Zero
- [x] A KEDA ScaledDeployment is created to scale the broker to 1 when the Knative serverless boots up(?)
```
